import Post from './Post'
import './styles/newspage/page_one_centre.css'
import './styles/newspage/page_one.css'
import './styles/newspage/newspage.css'
import './styles/contacts/contacts_questions.css'
import './styles/contacts/contacts_block1.css'
import './styles/products/products_styles.css'
import './styles/products/products_center.css'
import './styles/about/center.css'
import './styles/about/about_section.css'
import './styles/about/history.css'
import './styles/styles.css'
import './styles/burger.css'
import './styles/slider.css'
import './styles/section.css'
import './styles/main.css'
import './styles/news.css'
import './styles/footer.css'
import './newspage1.html'
import './about.html'
import './products.html'
import './contacts.html'
import './news.html'
import 'jquery'
import './burger'


const post = new Post('Webpack Post Title')

console.log('Post to String:', post.toString())